### PR TITLE
mouse: Accumulate fractional mouse data

### LINKED ISSUE #372: SDL_MOUSEMOTION events report incorrect relative motion
I'm on Arch Linux using sdl2-compat 2.30.52-1, X11. Tested that this works correctly on sdl2 2.16.0.

When moving the cursor single pixels at a time, the xrel and yrel fields report 0 instead of 1. Other cases are incorrect as well, there seems to be some accumulation going on that isn't reset/rounded properly. If you move the cursor large amounts and then by single pixels, xrel/yrel will still report those large coordinates in future mouse motion events.

### PR DESCRIPTION
**Pull request by cgutman**
This PR accumulates the floating point values returned in `SDL_EVENT_MOUSE_MOTION`, `SDL_EVENT_MOUSE_WHEEL`, and `SDL_GetRelativeMouseState()`.

For the events, I'm using global variables rather than per-window state which I _think_ should fine because only one window is receiving mouse input at a time.

Fixes #372

### CODE REVIEW

**Comment by slouken** [comment]
Is SDL_modff() helpful for this?

**Comment by slouken** [comment]
https://gist.github.com/slouken/7c41d29a252d58778794311f555ebe8c

**Comment by cgutman** [comment]
> Is SDL_modff() helpful for this?

We could use it, but it doesn't seem like it would end up much different in complexity than the current solution.

**Comment by slouken** [comment]
It wouldn't be dependent on the current rounding mode when you're casting to int...

**Comment by slouken** [comment]
Also, it would be nifty to actually use the fractional accumulation gist I wrote for GDC. :)

**Comment by cgutman** [comment]
> It wouldn't be dependent on the current rounding mode when you're casting to int...

Good point, updated the PR to use `SDL_modff()`.

File: src/sdl2_compat.c [hunk 1]
```diff
@@ -1685,14 +1714,14 @@ static SDL2_Event *Event3to2(const SDL_Event *event3, SDL2_Event *event2)
...
-            motion->yrel = (Sint32)event3->motion.yrel;
+            motion->xrel = (Sint32)AccumulateFloatValueToInteger(&relative_mouse_event_x_frac, event3->motion.xrel);
+            motion->yrel = (Sint32)AccumulateFloatValueToInteger(&relative_mouse_event_y_frac, event3->motion.yrel);
         } else {
             SDL2_MouseMotionEvent *motion = &event2->motion;
             motion->x = (Sint32)event3->motion.x;
             motion->y = (Sint32)event3->motion.y;
-            motion->xrel = (Sint32)event3->motion.xrel;
-            motion->yrel = (Sint32)event3->motion.yrel;
+            motion->xrel = (Sint32)AccumulateFloatValueToInteger(&relative_mouse_event_x_frac, event3->motion.xrel);
```
Comment (slouken) [inline src/sdl2_compat.c:1723]: Cast may not be needed here, definitely not needed below casting to int.

File: src/sdl2_compat.c [hunk 2]
```diff
@@ -1685,14 +1714,14 @@ static SDL2_Event *Event3to2(const SDL_Event *event3, SDL2_Event *event2)
...
+            motion->yrel = (Sint32)AccumulateFloatValueToInteger(&relative_mouse_event_y_frac, event3->motion.yrel);
         }
         break;
```
Comment (slouken) [inline src/sdl2_compat.c:1726]: Maybe drop the event if xrel and yrel are zero?

File: src/sdl2_compat.c (hunk 1 above)
Comment (cgutman) [reply src/sdl2_compat.c:1723]: I'll ditch the casts and see if CI stays happy on all platforms.

File: src/sdl2_compat.c (hunk 2 above)
Comment (cgutman) [reply src/sdl2_compat.c:1726]: I think we'd need more extensive refactoring to support `Event3to2()` deciding that an event should be dropped  entirely. Functions like `SDL_WaitEventTimeout()` and `SDL_PeepEvents()` are calling it and assuming a 1:1 mapping between SDL2 and SDL3 events.

If we woke up from `SDL_WaitEventTimeout()` with an event that we later decided to drop, we'd need to go back to sleep again while remembering how much time we had slept for previously.

There's also other corner cases like emulated mouse input via touch where we [purposely suppress the relative motion](https://github.com/libsdl-org/SDL/blob/b5297de56fc20af1f5c6d0decb1da7f3ade369e6/src/events/SDL_mouse.c#L743-L747) to avoid having massive relative deltas when the user taps different places on screen.

I think it's probably best to just send the extra events unless we discover something breaking due to them. That's also how it worked for `SDL_MOUSEWHEEL` back when we added the `preciseX` and `preciseY` fields. You'd get `SDL_MOUSEWHEEL` events with `x=0, y=0` (and non-zero `preciseX` and/or `preciseY`) until enough accumulated to roll x/y over to the next integer value.

Comment (slouken) [reply src/sdl2_compat.c:1726]: Sounds good.

**Comment by slouken** [comment]
Merged, thanks!
