### PR TITLE
fix(events): tolerate nullptr for event on peep

### LINKED ISSUE #286: PeepEvents seems unprepared for null event
When running [AntiMicroX](https://github.com/AntiMicroX/antimicrox) with `sdl2-compat` I get a `SIGSEGV`:

Backtrace with debug builds:
```Thread 36 (Thread 0x7fff7d9bf6c0 (LWP 18816) "sdlWorkerThread"):
#0  0x00007ffff7f705f1 in Event3to2 (event3=0x7fff5c001300, event2=0x0) at <...>/github.com/sdl2-compat/src/sdl2_compat.c:1341
#1  0x00007ffff7f71ae3 in SDL_PeepEvents_REAL (events2=0x0, numevents=1, action=SDL_GETEVENT, minType=0, maxType=65535) at <...>/github.com/sdl2-compat/src/sdl2_compat.c:1834
#2  0x00007ffff7f8db9b in SDL_PeepEvents (a=0x0, b=1, c=SDL_GETEVENT, d=0, e=65535) at <...>/github.com/sdl2-compat/src/dynapi/SDL_dynapi_procs.h:144
#3  0x0000555555896b99 in SDLEventReader::eventStatus (this=0x555555ea1e90) at <...>/github.com/antimicrox/src/sdleventreader.cpp:178
#4  0x00005555558969d8 in SDLEventReader::performWork (this=0x555555ea1e90) at <...>/github.com/antimicrox/src/sdleventreader.cpp:123
#5  0x00005555557f167e in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (SDLEventReader::*)()>::call(void (SDLEventReader::*)(), SDLEventReader*, void**) (f=(void (SDLEventReader::*)(class SDLEventReader * 
formWork()>, o=0x555555ea1e90, arg=0x7fff7d9becd0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#6  0x00005555557f1045 in QtPrivate::FunctionPointer<void (SDLEventReader::*)()>::call<QtPrivate::List<>, void>(void (SDLEventReader::*)(), SDLEventReader*, void**) (f=(void (SDLEventReader::*)(class SDLEventReader * const)) 0x5555558969b4
5ea1e90, arg=0x7fff7d9becd0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#7  0x00005555557f004b in QtPrivate::QSlotObject<void (SDLEventReader::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x5555562d42a0, r=0x555555ea1e90, a=0x7fff7d9becd0, ret=
impl.h:418
...
```

```
1340        /* for now, the timestamp field has grown in size (and precision), everything after it is currently the same, minus padding at the end, so bump the fields down. */
1341        event2->common.type = event3->type;
1342        event2->common.timestamp = (Uint32) SDL_NS_TO_MS(event3->common.timestamp);
```
```
(gdb) info args
event3 = 0x7fff5c001300
event2 = 0x0
```

Calling code:
```
int SDLEventReader::eventStatus()
{
    int result = 0;

    SDL_PumpEvents();

    switch (SDL_PeepEvents(nullptr, 1, SDL_GETEVENT, SDL_FIRSTEVENT, SDL_LASTEVENT))
```

Relates to https://github.com/AntiMicroX/antimicrox/issues/1129

### PR DESCRIPTION
**Pull request by skryvel**
Fixes #286 

Caveat I'm a SDL newbie -- I just went by the docs and what seemed to make sense. Let me know and I'll rework if needed. Fixed AntiMicroX use for me.

### CODE REVIEW

File: src/sdl2_compat.c [hunk 1]
```diff
@@ -1816,12 +1816,16 @@ SDL_DECLSPEC int SDLCALL
 SDL_PeepEvents(SDL2_Event *events2, int numevents, SDL_eventaction action, Uint32 minType, Uint32 maxType)
 {
     int isstack = 0;
-    SDL_Event *events3 = SDL3_small_alloc(SDL_Event, numevents ? numevents : 1, &isstack);
+    SDL_Event *events3 = 0;
```
Comment (slouken) [inline src/sdl2_compat.c:1819]:
```suggestion
    SDL_Event *events3 = NULL;
```

File: src/sdl2_compat.c [hunk 2]
```diff
@@ -1830,12 +1834,15 @@ SDL_PeepEvents(SDL2_Event *events2, int numevents, SDL_eventaction action, Uint3
         retval = SDL3_PeepEvents(events3, numevents, action, minType, maxType);
     } else {  /* SDL2 assumes it's SDL_PEEKEVENT if it isn't SDL_ADDEVENT or SDL_GETEVENT. */
         retval = SDL3_PeepEvents(events3, numevents, action, minType, maxType);
-        for (i = 0; i < retval; i++) {
+        for (i = 0; i < retval && events3; i++) {
```
Comment (slouken) [inline src/sdl2_compat.c:1837]:
```suggestion
        if (events3) {
            for (i = 0; i < retval; i++) {
```

**Comment by slouken** [comment]
This generally looks good! I've added a few comments, can you address them and then I'll merge this?

**Comment by skryvel** [comment]
> This generally looks good! I've added a few comments, can you address them and then I'll merge this?

Thanks. Fixing. I realized I have a question -- what to do if action is `SDL_ADDEVENT` and the even is null? Now that the allocation is conditional.

**Comment by slouken** [comment]
> > This generally looks good! I've added a few comments, can you address them and then I'll merge this?
> 
> Thanks. Fixing. I realized I have a question -- what to do if action is `SDL_ADDEVENT` and the even is null? Now that the allocation is conditional.

SDL3 will return an error.

File: src/sdl2_compat.c [hunk 3]
```diff
@@ -1816,12 +1816,16 @@ SDL_DECLSPEC int SDLCALL
...
     int isstack = 0;
-    SDL_Event *events3 = SDL3_small_alloc(SDL_Event, numevents ? numevents : 1, &isstack);
+    SDL_Event *events3 = NULL;
     int retval = 0;
     int i;
 
-    if (!events3) {
-        return -1;
+    // For GET/PEEK the event may be NULL, so avoid allocation.
+    if (events2 || (action == SDL_ADDEVENT)) {
```
Comment (slouken) [inline src/sdl2_compat.c:1824]:
```suggestion
    if (events2) {
```

File: src/sdl2_compat.c [hunk 4]
```diff
@@ -1816,12 +1816,16 @@ SDL_DECLSPEC int SDLCALL
...
+        events3 = SDL3_small_alloc(SDL_Event, numevents ? numevents : 1, &isstack);
+        if (!events3) {
+            return -1;
+        }
     }
     if (action == SDL_ADDEVENT) {
         for (i = 0; i < numevents; i++) {
```
Comment (slouken) [inline src/sdl2_compat.c:1831]: Should check for NULL here too.

**Comment by skryvel** [comment]
> > > This generally looks good! I've added a few comments, can you address them and then I'll merge this?
> > 
> > 
> > Thanks. Fixing. I realized I have a question -- what to do if action is `SDL_ADDEVENT` and the even is null? Now that the allocation is conditional.
> 
> SDL3 will return an error.

I should've written what I was thinking. It is that `Event2to3` will access a null pointer before reaching SDL3. Assuming `numevents > 0`.
