### PR TITLE
Fixed SDL_RenderReadPixels when format argument is 0

### LINKED ISSUE #406: SDL_RenderReadPixels fails when format argument is 0
I've been using SDL_RenderReadPixels to implement screenshots in my SDL2 application for a while, but this does not work when run through sdl2-compat. I'm not sure if this is a problem with my code or a bug in sdl2-compat. Here is a minimal C++ example that demonstrates the issue:
    
    #include <SDL.h>
    #include <SDL_stdinc.h>
    
    void take_screenshot(SDL_Renderer* const renderer) {
        SDL_Surface* surface {SDL_CreateRGBSurfaceWithFormat(
                0,          //flags
                640,        //width
                480,        //height
                32,         //bit depth
                SDL_PIXELFORMAT_ARGB8888)};
        SDL_LockSurface(surface);
        SDL_RenderReadPixels(
                renderer,
                nullptr,    //source rectangle (full)
                0,          //format (use target format) 
                surface->pixels,
                surface->pitch);
        SDL_Log(
                "The color of the top left corner pixel is #%06X",
                reinterpret_cast<Uint32*>(surface->pixels)[0]);
        SDL_UnlockSurface(surface);
        SDL_SetRenderTarget(renderer, nullptr);
        SDL_SaveBMP(surface, "./window.bmp");
    }
    
    int main(int argc, char* argv[]) {
        SDL_Init(SDL_INIT_VIDEO);
        SDL_Window* window {SDL_CreateWindow(
                "SDL_RenderReadPixels Test",
                SDL_WINDOWPOS_UNDEFINED,
                SDL_WINDOWPOS_UNDEFINED,
                640,
                480,
                0   //flags
        )};
        SDL_Renderer* renderer {SDL_CreateRenderer(
                window,
                -1, //driver
                0   //flags
        )};
        SDL_Texture* texture {SDL_CreateTexture(
                renderer,
                SDL_PIXELFORMAT_ARGB8888,
                SDL_TEXTUREACCESS_STREAMING,
                640,
                480)};
    
        SDL_Event event;
        bool quit {false};
        SDL_Log("%s", "Press s to save a screenshot at ./window.bmp.");
        for (Uint32 frame {0}; !quit; ++frame) {
            //Render to window:
            {
                int pitch;
                Uint32* pixels;
                SDL_LockTexture(
                        texture,
                        nullptr,    //source rectangle (full)
                        reinterpret_cast<void**>(&pixels),
                        &pitch);
                for (int row {0}; row < 480; ++row) {
                    for (int column {0}; column < 640; ++column) {
                        pixels[row * (pitch / sizeof(Uint32)) + column] = row * column + frame * 8; //moving pattern
                    }
                }
                SDL_UnlockTexture(texture);
                SDL_RenderCopy(renderer, texture, nullptr, nullptr);
            }
    
            while (SDL_PollEvent(&event)) {
                switch (event.type) {
                    case SDL_QUIT:
                        quit = true;
                        break;
                    case SDL_KEYDOWN:
                        switch (event.key.keysym.scancode) {
                            case SDL_SCANCODE_S:
                                take_screenshot(renderer);
                                SDL_Log("%s", "Saved screenshot at ./window.bmp.");
                            break;
                        }
                        break;
                }
            }
    
            SDL_RenderPresent(renderer);
        }
    
        return 0;
    }

When running normally (dynamically loading SDL2), I press the s key repeatedly and get the following output:

    $ ./main 
    INFO: Press s to save a screenshot at ./window.bmp.
    INFO: The color of the top left corner pixel is #00C620
    INFO: Saved screenshot at ./window.bmp.
    INFO: The color of the top left corner pixel is #00ECA8
    INFO: Saved screenshot at ./window.bmp.
    INFO: The color of the top left corner pixel is #01EA78
    INFO: Saved screenshot at ./window.bmp.

This correctly produces a screenshot of the window contents like this:
Image

The same program produces the following output when forced to run through sdl2-compat:

    $ LD_LIBRARY_PATH=/tmp/test/SDL/build:/tmp/test/sdl2-compat/build SDL2COMPAT_DEBUG_LOGGING=1 ./main 
    sdl2-compat 2.32.53, built on Mar 11 2025 at 22:38:52, talking to SDL3 3.3.0
    sdl2-compat: This app appears to be named: main
    INFO: Press s to save a screenshot at ./window.bmp.
    INFO: The color of the top left corner pixel is #000000
    INFO: Saved screenshot at ./window.bmp.
    INFO: The color of the top left corner pixel is #000000
    INFO: Saved screenshot at ./window.bmp.
    INFO: The color of the top left corner pixel is #000000
    INFO: Saved screenshot at ./window.bmp.

And it produces a fully black screenshot:
Image

### PR DESCRIPTION
**Pull request by Hypnotron**
This should resolve #406. I tried to match the behavior of SDL2's implementation of [SDL_RenderReadPixels](https://github.com/libsdl-org/SDL/blob/1caae3e9e448e9ec728faa9b13e058f5d63189e0/src/render/SDL_render.c#L4233C1-L4239C6).

### CODE REVIEW

File: src/sdl2_compat.c [hunk 1]
```diff
@@ -6133,11 +6133,22 @@ SDL_DECLSPEC int SDLCALL
...
     if (!surface) {
         return -1;
     }
+   
+    if (!format) {
+        target = SDL3_GetRenderTarget(renderer);
+        if (!target) {
+            format = SDL3_GetWindowPixelFormat(SDL3_GetPointerProperty(SDL3_GetRendererProperties(renderer), SDL_PROP_RENDERER_WINDOW_POINTER, NULL));
+        }           
+        else {
```
Comment (slouken) [inline src/sdl2_compat.c:6148]: This patch looks great, and once you match the SDL style, I'll be happy to merge it.

The SDL style is:
```c
if (condition) {
} else {
}
```
Also, usually the if condition is a positive one, so it would be:
```c
if (target) {
} else {
}
```

**Comment by Hypnotron** [comment]
I've pushed a new commit to fix the style as well as the -fpermissive build errors.

**Comment by slouken** [comment]
Merged, thanks!
